import { Request, Response } from "express";
import { prisma } from "../lib/prisma";
import axios from "axios";
import { progressService } from "../services/progress.service";

const AI_SERVICE_URL = process.env.FASTAPI_URL || "http://localhost:8000";

/**
 * Submit a quiz attempt
 */
export const submitQuizAttempt = async (req: Request, res: Response) => {
  try {
    const userId = req.user?.id;
    const { topicContentId, answers, timeSpent } = req.body;

    if (!userId) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    // Get the stored quiz for this topic
    const quiz = await prisma.quiz.findFirst({
      where: { topicContentId },
      include: { topicContent: true },
    });

    if (!quiz) {
      return res.status(404).json({ error: "Quiz not found for this topic" });
    }

    // Calculate score
    const { score, correctAnswers, feedback } = calculateScore(
      quiz.questions,
      answers,
    );

    const passed = score >= (quiz.passingScore || 70);

    // Save attempt
    const attempt = await prisma.quizAttempt.create({
      data: {
        userId,
        topicContentId,
        quizId: quiz.id,
        answers,
        score,
        totalQuestions: quiz.totalQuestions,
        correctAnswers,
        timeSpent: timeSpent || null,
        result: passed,
      },
    });

    const passingScore = quiz.passingScore || 70;
    const passed = score >= passingScore;

    if (passed) {
      await progressService.completeTopic(
        quiz.topicContent.roadmapId,
        userId,
        quiz.topicContent.phaseId,
        quiz.topicContent.topicId,
      );
    }

    res.json({
      attemptId: attempt.id,
      score,
      correctAnswers,
      totalQuestions: quiz.totalQuestions,
      feedback,
      result: passed,
      passed,
    });
  } catch (error: any) {
    console.error("Error submitting quiz attempt:", error);
    res.status(500).json({ error: error.message });
  }
};

/**
 * Get quiz history for a topic
 */
export const getQuizHistory = async (req: Request, res: Response) => {
  try {
    const userId = req.user?.id;
    const { topicContentId } = req.params as { topicContentId: string };

    if (!userId) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    const attempts = await prisma.quizAttempt.findMany({
      where: {
        userId,
        topicContentId,
      },
      orderBy: { completedAt: "desc" },
    });

    res.json(attempts);
  } catch (error: any) {
    console.error("Error fetching quiz history:", error);
    res.status(500).json({ error: error.message });
  }
};

/**
 * Generate quiz for a topic (calls AI service)
 */
export const generateQuizForTopic = async (req: Request, res: Response) => {
  try {
    const { topicContentId } = req.params as { topicContentId: string };
    console.log(
      `[Quiz Controller] Received generation request for topicContentId: ${topicContentId}`,
    );

    // 1. Check if valid quiz exists in Quiz table
    const existingQuiz = await prisma.quiz.findFirst({
      where: { topicContentId },
    });

    if (existingQuiz) {
      console.log(
        `[Quiz Controller] Returning existing quiz from Quiz table for ${topicContentId}`,
      );
      // Return without answers/explanations
      return res.json(sanitizeQuiz(existingQuiz));
    }

    // 2. Get topic content to generate
    const topicContent = await prisma.topicContent.findUnique({
      where: { id: topicContentId },
      include: {
        roadmap: true,
      },
    });

    if (!topicContent) {
      return res.status(404).json({ error: "Topic content not found" });
    }

    // 3. Call AI service to generate quiz
    const aiResponse = await axios.post(
      `${AI_SERVICE_URL}/api/v1/quiz/generate`,
      {
        goal: (topicContent as any).roadmap.goal,
        phase_title: topicContent.phaseTitle,
        topic_title: topicContent.topicTitle,
        topic_content: topicContent.content,
      },
    );

    const quizData = aiResponse.data;

    // Validate quiz structure
    if (
      !quizData ||
      !Array.isArray(quizData.questions) ||
      quizData.questions.length === 0
    ) {
      console.error("Invalid quiz generated by AI:", quizData);
      return res.status(503).json({
        error:
          "Failed to generate valid quiz questions. AI Service might be overloaded.",
        details: quizData,
      });
    }

    // 4. Save to Quiz table
    const savedQuiz = await prisma.quiz.create({
      data: {
        topicContentId,
        questions: quizData.questions, // Stores full questions with answers
        answers: {}, // Optional: could extract answers here if needed
        totalQuestions:
          quizData.metadata?.totalQuestions || quizData.questions.length,
        explanation: {}, // Optional
        difficulty: "mixed",
        concept: "",
        sourceSection: "",
        learningObjective: "",
        passingScore: quizData.metadata?.passingScore || 70,
        estimatedTime: parseInt(
          String(quizData.metadata?.estimatedTime).replace(/\D/g, "") || "10",
        ),
        difficultyBreakdown: quizData.metadata?.difficultyBreakdown || {},
        conceptCoverage: quizData.metadata?.conceptCoverage || {},
        codeQuestionCount: quizData.metadata?.codeQuestionCount || 0,
      },
    });

    // 6. Return sanitized quiz
    res.json(sanitizeQuiz(savedQuiz));
  } catch (error: any) {
    console.error("Error generating quiz:", error);
    res.status(500).json({ error: error.message });
  }
};

/**
 * Remove sensitive data (answers, explanations) from quiz response
 */
function sanitizeQuiz(quiz: any) {
  const questions = quiz.questions; // quiz.questions is Json type from Prisma
  if (!Array.isArray(questions)) return { questions: [] };

  const sanitizedQuestions = questions.map((q: any) => {
    const { correctAnswer, explanation, ...safeQuestion } = q; // Exclude correct answer and explanation
    return safeQuestion;
  });

  return {
    ...quiz,
    questions: sanitizedQuestions,
  };
}

/**
 * Get user's best attempt for a topic
 */
export const getBestAttempt = async (req: Request, res: Response) => {
  try {
    const userId = req.user?.id;
    const { topicContentId } = req.params as { topicContentId: string };

    if (!userId) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    const bestAttempt = await prisma.quizAttempt.findFirst({
      where: {
        userId,
        topicContentId,
      },
      orderBy: { score: "desc" },
    });

    if (!bestAttempt) {
      return res.status(404).json({ error: "No attempts found" });
    }

    res.json(bestAttempt);
  } catch (error: any) {
    console.error("Error fetching best attempt:", error);
    res.status(500).json({ error: error.message });
  }
};

/**
 * Get quiz status for a topic (by roadmap/phase/topic IDs)
 */
export const getQuizStatus = async (req: Request, res: Response) => {
  try {
    const userId = req.user?.id;
    const { roadmapId, phaseId, topicId } = req.query as {
      roadmapId: string;
      phaseId: string;
      topicId: string;
    };

    if (!userId) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    if (!roadmapId || !phaseId || !topicId) {
      return res.status(400).json({ error: "Missing required parameters" });
    }

    // Find topic content
    const topicContent = await prisma.topicContent.findUnique({
      where: {
        roadmapId_phaseId_topicId: {
          roadmapId,
          phaseId,
          topicId,
        },
      },
      include: {
        quizAttempts: {
          where: { userId },
          orderBy: { score: "desc" },
          take: 1,
        },
      },
    });

    if (!topicContent) {
      // Content doesn't exist yet (hasn't been viewed/cached)
      return res.json({
        exists: false,
        hasQuiz: false,
        topicContentId: null,
      });
    }

    // Check if quiz exists in the new Quiz table
    const quiz = await prisma.quiz.findFirst({
      where: { topicContentId: topicContent.id },
    });

    const hasQuiz = !!quiz;

    // Get best score
    const bestAttempt = await prisma.quizAttempt.findFirst({
      where: {
        topicContentId: topicContent.id,
        userId,
      },
      orderBy: { score: "desc" },
    });

    res.json({
      exists: true,
      hasQuiz,
      topicContentId: topicContent.id,
      bestScore: bestAttempt?.score || null,
    });
  } catch (error: any) {
    console.error("Error checking quiz status:", error);
    res.status(500).json({ error: error.message });
  }
};

/**
 * Calculate quiz score
 */
function calculateScore(
  quizQuestions: any,
  userAnswers: Record<number, string>,
) {
  let correctAnswers = 0;
  const feedback: any[] = [];

  const questions = quizQuestions as any[]; // quizQuestions from Prisma Json type

  questions.forEach((question: any) => {
    const userAnswer = userAnswers[question.id];
    const isCorrect = userAnswer === question.correctAnswer;

    if (isCorrect) {
      correctAnswers++;
    }

    feedback.push({
      questionId: question.id,
      question: question.question,
      userAnswer,
      correctAnswer: question.correctAnswer,
      isCorrect,
      explanation: question.explanation,
    });
  });

  const score = (correctAnswers / questions.length) * 100;

  return {
    score: Math.round(score * 10) / 10, // Round to 1 decimal
    correctAnswers,
    feedback,
  };
}
